{{- if not .Values.existingConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    {{- if .Values.configOverride }}
      {{- .Values.configOverride | indent 2 }}
    {{- else }}

      {{- if .Values.ports.mqtt.enabled }}
    listener {{ .Values.ports.mqtt.port }}
      {{- end }}

      {{- if .Values.ports.websocket.enabled }}
    listener {{ .Values.ports.websocket.port }}
    protocol websockets
      {{- end }}

      {{- if .Values.ports.mqtts.enabled }}
    listener {{ .Values.ports.mqtts.port }}
    certfile {{ .Values.ports.mqtts.certPath }}
    keyfile {{ .Values.ports.mqtts.keyPath }}
      {{- end }}

      {{- if .Values.auth.allowAnonymous }}
    allow_anonymous true
      {{- else }}
    allow_anonymous false
      {{- end }}

      {{- if .Values.persistence.enabled }}
    persistence true
    persistence_location {{ .Values.persistence.mountPath }}
    autosave_interval 1800
      {{- end }}

    auth_plugin /mosquitto/go-auth.so
      {{- include "mosquitto.auth.backends" .Values.auth | nindent 4 }}

    auth_opt_hasher {{ .Values.auth.hasher }}

    auth_opt_check_prefix {{ .Values.auth.checkPrefixes }}
      {{- if .Values.auth.checkPrefixes }}
        {{- include "mosquitto.auth.prefixes" .Values.auth | nindent 4 }}
      {{- end }}

      {{- if .Values.auth.files.enabled }}
        {{- include "mosquitto.auth.files.config" . | nindent 4 -}}
      {{- end }}
      {{- if .Values.auth.jwt.enabled }}
        {{- include "mosquitto.auth.jwt.config" . | nindent 4 -}}
      {{- end }}

      {{- if .Values.configExtra }}
        {{- .Values.configExta | indent 2 }}
      {{- end }}
    {{- end }}

{{- end }}
