{{- if or .Values.ports.mqtts.enabled (or .Values.auth.files.enabled (and .Values.auth.jwt.enabled (or (eq .Values.auth.jwt.mode "js") (eq .Values.auth.jwt.mode "files")))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.ports.mqtts.enabled }}
  certfile: {{ .Values.ports.mqtts.cert | b64enc | quote }}
  keyfile: {{ .Values.ports.mqtts.key | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.files.enabled .Values.auth.files.passwordEntries }}
  passwordfile: {{ .Values.auth.files.passwordEntries | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.files.enabled .Values.auth.files.acls }}
  aclfile: {{ .Values.auth.files.acls | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.jwt.enabled (eq .Values.auth.jwt.mode "js") }}
  jwtJsUserScript: {{ .Values.auth.jwt.jwtJsUserScript | b64enc | quote }}
  jwtJsSuperuserScript: {{ .Values.auth.jwt.jwtJsSuperuserScript | b64enc | quote }}
  jwtJsAclScript: {{ .Values.auth.jwt.jwtJsAclScript | b64enc | quote }}
  {{- end }}
  {{- if and .Values.auth.jwt.enabled (eq .Values.auth.jwt.mode "files") }}
  jwtFilesAcl: {{ .Values.auth.jwt.jwtFilesAcl | b64enc | quote }}
  {{- end }}
{{- end }}
